"""Pridani sloupcu is_admin a force_password_change do app_users

Revision ID: 9b9559c8d778
Revises: 
Create Date: 2025-12-10 16:28:48.273590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9559c8d778'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('app_users', sa.Column('force_password_change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_users', 'force_password_change')
    op.drop_column('app_users', 'is_admin')
    # ### end Alembic commands ###
